imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

parameters:
    cash_on_delivery_fee: 20
    priority_shipment_fee: 9
    economy_shipment_fee: 7
    newest_products_count: 12
    payment_period: 10 #in days

framework:
    #esi:             ~
    translator:      { fallback: de }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
      engines:
        - 'twig'
    session:
        default_locale: %locale%
        lifetime:       7200
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: %java_binary%
    filters:
        cssrewrite: ~
        sass: ~
        compass:
          bin: %compass_binary%
        cssmin: ~
        closure:
          jar: %kernel.root_dir%/../vendor/closure-compiler.jar
        yui_css:
          jar: %kernel.root_dir%/../vendor/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

jms_i18n_routing:
    default_locale: de
    locales: [de, en]
    strategy: prefix

stof_doctrine_extensions:
    default_locale: de_CH
    orm:
        default:
          timestampable: true

avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web
    cache_prefix: cache/media
    driver:       gd
    filters:
        cart:
            type:    thumbnail
            options: { size: [150, 150], mode: inbound, quality: 60, format: jpeg }
        checkout:
            type:    thumbnail
            options: { size: [75, 75], mode: inbound, quality: 60, format: jpeg }
        featured_product:
            type:    thumbnail
            options: { size: [300, 475], mode: inbound, quality: 60, format: jpeg }
        product_preview:
            type:    thumbnail
            options: { size: [225, 350], mode: inbound, quality: 60, format: jpeg }
        product_detail:
            type:    thumbnail
            options: { size: [400, 600], mode: inset, quality: 60, format: jpeg }