index:
    pattern:  /
    defaults: { _controller: shop.frontend.controller.index:indexAction }

ShopCommonBundle:
    resource: "@ShopCommonBundle/Controller/"
    type:     annotation
    prefix:   /_common

ShopBackendBundle:
    resource: "@ShopBackendBundle/Controller/"
    type:     annotation
    prefix:   /_admin

ShopFrontendBundle:
    resource: "@ShopFrontendBundle/Controller/"
    type:     annotation
    prefix:   /shop

_imagine:
    resource: .
    type:     imagine

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
