security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Shop\CommonBundle\Entity\User:
          algorithm: sha512
          iterations: 1000
          encode_as_base64: true
        Shop\CommonBundle\Entity\Customer:
          algorithm: sha512
          iterations: 1000
          encode_as_base64: true

    # role_hierarchy:
    #     ROLE_ADMIN:       ROLE_USER
    #     ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        backend_user:
          entity: { class: Shop\CommonBundle\Entity\User, property: email }
        customer:
          entity: { class: Shop\CommonBundle\Entity\Customer, property: email }

    firewalls:
        login_firewall:
          pattern: ^/((de|en)/)?(_admin/)?sessions/new
          anonymous:
        admin:
          pattern: ^/((de|en)/)?_admin
          form_login:
            login_path: shop_backend_sessions_new
            check_path: shop_backend_sessions_create
            default_target_path: shop_backend_sessions_created
            always_use_default_target_path: true
            username_parameter: 'shop_commonbundle_sessiontype[username]'
            password_parameter: 'shop_commonbundle_sessiontype[password]'
            post_only: true
            use_forward: false
          logout:
            path: shop_backend_sessions_destroy
            target: shop_backend_sessions_new
          provider: backend_user
        frontend:
          pattern: ^/((de|en)/)?shop
          form_login:
            login_path: shop_backend_sessions_new
            check_path: shop_backend_sessions_create
            default_target_path: shop_backend_sessions_created
            always_use_default_target_path: true
            username_parameter: 'shop_commonbundle_sessiontype[username]'
            password_parameter: 'shop_commonbundle_sessiontype[password]'
            post_only: true
            use_forward: false
          logout:
            path: shop_backend_sessions_destroy
            target: shop_backend_sessions_new
          provider: customer
          anonymous: ~
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
